#!/bin/bash

set -e

main() {
    check curl
}

# check(command, package=None)
check() {
    if command -v "$1" > /dev/null; then
        return
    fi

    local PACKAGE="$2"

    if [ -z "$PACKAGE" ]; then
        PACKAGE="$1"
    fi
    echo "Installing $PACKAGE"
    sudo apt install "$PACKAGE"
}

main "$@"
